name: dante

services:
  dante:
    build:
      context: .
      dockerfile: Dockerfile
    image: dante
    container_name: dante
    init: true
    ports:
      - "1080:1080"
    environment:
      PROXY_USER: proxy_user
      PROXY_PASSWORD: change-me
    volumes:
      - ./sockd.conf:/etc/sockd.conf:ro
    restart: always
